import { db, Categorias, Menu } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
	await db.insert(Categorias).values([
		{name: "Entradas", id: "1"},
		{name: "Tablas", id: "2"},
		{name: "Ensaladas", id: "3"},
		{name: "Cocina rápida", id: "4"},
		{name: "Carnes de la parrilla", id: "5"},
		{name: "Carnes de la cocina", id: "6"},
		{name: "Nuestras pastas", id: "7"},
		{name: "Guarniciones", id: "8"},
		{name: "Cafeteria", id: "9"},
		{name: "Bebidas", id: "10"},
	])

	await db.insert(Menu).values([
		{category_id: "1", name: "Empanada criolla", price: 1500, id: "1", ingredientes: ""},
		{category_id: "1", name: "Empanada de cebolla y queso", price: 1500, id: "2", ingredientes: ""},
		{category_id: "1", name: "Provoleta a la parrilla", price: 6200, id: "3", ingredientes: ""},
		{category_id: "1", name: "Provoleta con verduras", price: 7800, id: "4", ingredientes: ""},
		{category_id: "1", name: "Jamón crudo con palmitos", price: 10500, id: "5", ingredientes: ""},
		{category_id: "1", name: "Rabas a la romana", price: 9500, id: "6", ingredientes: ""},
		{category_id: "1", name: "Creppe de espinaca", price: 5800, id: "7", ingredientes: ""},

		{category_id: "2", name: "Tabla gringa", price: 10700, id: "8", ingredientes: "salame y variedad de quesos"},
		{category_id: "2", name: "Tabla especial", price: 11900, id: "9", ingredientes: "jamón crudo, jamón cocido y salame de la Colonia"},
		{category_id: "2", name: "Tabla de quesos", price: 11600, id: "10", ingredientes: "provolone, roquefort, tybo, gruyere, fontina y frutas secas"},
		{category_id: "2", name: "Tabla de salame de la Colonia", price: 10500, id: "11", ingredientes: ""},

		{category_id: "3", name: "Mediterránea", ingredientes: "hojas de lechuga, jamón cocido, queso, tomatitos cherry y aceitunas negras", price: 9800, id: "12"},
		{category_id: "3", name: "Californiana", ingredientes: "tomate, palta, palmitos, granos de choclo y salsa golf", price: 10500, id: "13"},
		{category_id: "3", name: "Del Cesar", ingredientes: "lechuga, queso y pollo en tiras", price: 9900, id: "14"},
		{category_id: "3", name: "De futros del Mar", ingredientes: "manzana verde, camarones y apio", price: 11900, id: "15"},
		{category_id: "3", name: "De Atún", ingredientes: "atún, lechuga, huevo duro, aceitunas negras, tomates secos", price: 9900, id: "16"},
		{category_id: "3", name: "Panache de Verduras", ingredientes: "remolacha, huevo duro, chaucha, brócoli, papa al natural", price: 9500, id: "17"},

		{ category_id: "4",name: "Milanesa de ternera", price: 9500, id: "18", ingredientes: "" },
		{ category_id: "4",name: "Milanesa napolitana", price: 7900, id: "19", ingredientes: "" },
		{ category_id: "4",name: "Suprema de pollo", price: 6900, id: "20", ingredientes: "" },
		{ category_id: "4",name: "Suprema napolitana", price: 9500, id: "21", ingredientes: "" },
		{ category_id: "4",name: "Tortilla de papa", price: 5200, id: "22", ingredientes: "" },
		{ category_id: "4",name: "Tortilla española", price: 5700, id: "23", ingredientes: "" },
		{ category_id: "4",name: "Tortilla de espinaca", price: 5200, id: "24", ingredientes: "" },
		{ category_id: "4",name: "Omelette de queso", price: 4200, id: "25", ingredientes: "" },
		{ category_id: "4",name: "Omelette de jamón y queso", price: 4900, id: "26", ingredientes: "" },

		{ category_id: "5", name: "Parrillada Tipíca", ingredientes: "Empanada, Chorizo, Molleja, Chinchulin, Cuadril, Cerdo, Matambre, Costilla, Ensalada mixta, Papas fritas con huevos revueltos", price: 20500, id: "27"},
		{ category_id: "5", name: "Chivito", ingredientes: "", price: 18800, id: "28"},
		{ category_id: "5", name: "Asado de tira", ingredientes: "", price: 11500, id: "29"},
		{ category_id: "5", name: "Matambre de ternera", ingredientes: "", price: 11500, id: "30"},
		{ category_id: "5", name: "Matambrito de cerdo", ingredientes: "", price: 11500, id: "31"},
		{ category_id: "5", name: "Cuadrilcitos", ingredientes: "", price: 11900, id: "32"},
		{ category_id: "5", name: "Entrecotte", ingredientes: "", price: 12500, id: "33"},
		{ category_id: "5", name: "Bife de lomo", ingredientes: "", price: 13800, id: "34"},
		{ category_id: "5", name: "Molleja", ingredientes: "", price: 19500, id: "35"},
		{ category_id: "5", name: "Pailard de lomo", ingredientes: "", price: 15500, id: "36"},
		{ category_id: "5", name: "Bife de chorizo", ingredientes: "", price: 13500, id: "37"},
		{ category_id: "5", name: "1/2 pollo deshuesado", ingredientes: "", price: 8900, id: "38"},
		{ category_id: "5", name: "1/4 pollo deshuesado", ingredientes: "", price: 6500, id: "39"},
		{ category_id: "5", name: "Chorizo ó morcilla ó chinchulín", ingredientes: "", price: 6200, id: "40"},
		{ category_id: "5", name: "Brochette de lomo", ingredientes: "", price: 15500, id: "41"},
		{ category_id: "5", name: "Brochette mixto", ingredientes: "", price: 12800, id: "42"},
		{ category_id: "5", name: "Brochette de pollo", ingredientes: "", price: 10500, id: "43"},

		{ category_id: "6", name: "Lomo al champignon", ingredientes: "con salsa de champignon y papas españolas", price: 18500, id: "44"},
		{ category_id: "6", name: "Lomo a la pimienta", ingredientes: "crema de pimienta negra con papas a la crema", price: 17500, id: "45"},
		{ category_id: "6", name: "Entrecotte al verdeo", ingredientes: "crema de cebolla de verdeo y papas españolas", price: 15900, id: "46"},
		{ category_id: "6", name: "Mollejitas", ingredientes: "salteado al oliva con papas españolas", price: 20500, id: "47"},
		{ category_id: "6", name: "Cerdo de Los Cabritos", ingredientes: "al vino tinto con ciruelas", price: 14500, id: "48"},
		{ category_id: "6", name: "Cerdo a la Riojana", ingredientes: "a la plancha con jamón, pimiento, arvejas, huevo y papas regilla", price: 13000, id: "49"},
		{ category_id: "6", name: "Matambrito de cerdo al verdeo", ingredientes: "crema de cebolla de verdeo y papas españolas", price: 15500, id: "50"},
		{ category_id: "6", name: "Deshuesado de Los Cabritos", ingredientes: "al vino blanco con esparragos y alcauciles y papas noisette", price: 20500, id: "51"},
		{ category_id: "6", name: "Deshuesado al champignon", ingredientes: "salsa de champignon y papas españolas", price: 14500, id: "52"},
		{ category_id: "6", name: "Deshuesado a la cereza", ingredientes: "con cerezas, ananá y papas paille", price: 19000, id: "53"},
		{ category_id: "6", name: "Riñoncitos al vino blanco", ingredientes: "con puré de papas", price: 11900, id: "54"},
		{ category_id: "6", name: "Suprema Pastora", ingredientes: "arrollado con jamón, morrón, queso, salsa rosa y papas noisette", price: 15000, id: "55"},
		{ category_id: "6", name: "Lomito de atún Grille", ingredientes: "con verduras salteadas en oliva", price: 12500, id: "56"},
		{ category_id: "6", name: "Lenguado Grille", ingredientes: "con verduras salteadas en oliva", price: 13500, id: "57"},
		{ category_id: "6", name: "Paella del Rancho", ingredientes: "frutos del mar con arroz, pollo, espárragos y arvejas", price: 20500, id: "58"},


		{ category_id: "7", name: "Tallarines de Los Cabritos", ingredientes: "salteados con camarones", price: 12500, id: "59"},
		{ category_id: "7", name: "Ravioles negros", ingredientes: "rellenos con salmón con salsa de queso", price: 14800, id: "60"},
		{ category_id: "7", name: "Tallarines al huevo ó de espinaca", ingredientes: "", price: 7900, id: "61"},
		{ category_id: "7", name: "Ravioles al huevo", ingredientes: "rellenos de carne y verduras", price: 8900, id: "62"},
		{ category_id: "7", name: "Ravioles de espinaca", ingredientes: "rellenos de ricota y espinacas", price: 8900, id: "63"},
		{ category_id: "7", name: "Capelettis", ingredientes: "", price: 9700, id: "64"},
		{ category_id: "7", name: "Sorrentinos", ingredientes: "queso y jamón cocido/ de verduras/ caprese", price: 8900, id: "65"},
		{ category_id: "7", name: "Sorrentinos de calabaza", ingredientes: "salteados en oliva", price: 8900, id: "66"},
		{ category_id: "7", name: "Raviolon cuatro quesos", ingredientes: "", price: 8900, id: "67"},
		{ category_id: "7", name: "Lasagnas", ingredientes: "pollo y acelga/ carne y jamón y queso", price: 12500, id: "68"},
		{ category_id: "7", name: "Lasagna verde", ingredientes: "espinacas, champignones y tomates secos", price: 12500, id: "69"},
		{ category_id: "7", name: "Malfatti de espinaca y ricota", ingredientes: "", price: 8900, id: "70"},
		{ category_id: "7", name: "Ñoquis de papa", ingredientes: "", price: 8700, id: "71"},
		{ category_id: "7", name: "Ñoquis rellenos", ingredientes: "de papa, rellenos de queso", price: 9800, id: "72"},

		{ category_id: "8", name: "Papas fritas", ingredientes: "", price: 3500, id: "73"},
		{ category_id: "8", name: "Revuelto de papas con huevo", ingredientes: "", price: 4200, id: "74"},
		{ category_id: "8", name: "Papas al natural", ingredientes: "", price: 3500, id: "75"},
		{ category_id: "8", name: "Papas a la crema", ingredientes: "", price: 4200, id: "76"},
		{ category_id: "8", name: "Puré de papas / calabaza / mixto", ingredientes: "", price: 3500, id: "77"},
		{ category_id: "8", name: "Puré de manzana", ingredientes: "", price: 3500, id: "78"},
		{ category_id: "8", name: "Brócoli gratinado", ingredientes: "", price: 4700, id: "79"},
		{ category_id: "8", name: "Espinacas a la crema", ingredientes: "", price: 4700, id: "80"},
		{ category_id: "8", name: "Verduras braseadas a la parrilla", ingredientes: "", price: 5300, id: "81"},

		
		{ category_id: "9", name: "Café", ingredientes: "", price: 1700, id: "82"},
		{ category_id: "9", name: "Café en jarrito", ingredientes: "", price: 1900, id: "83"},
		{ category_id: "9", name: "Café doble", ingredientes: "", price: 2400, id: "84"},
		{ category_id: "9", name: "Café con crema", ingredientes: "", price: 2000, id: "85"},
		{ category_id: "9", name: "Té", ingredientes: "", price: 1700, id: "86"},

		{ category_id: "10", name: "Gaseosa", ingredientes: "", price: 2000, id: "87"},
		{ category_id: "10", name: "Aguas saborizadas", ingredientes: "", price: 2100, id: "88"},
		{ category_id: "10", name: "Jugo de naranja natural", ingredientes: "", price: 3600, id: "89"},
		{ category_id: "10", name: "Agua mineral con o sin gas", ingredientes: "", price: 2000, id: "90"},
		{ category_id: "10", name: "Limonada en jarra", ingredientes: "", price: 5600, id: "91"},
		{ category_id: "10", name: "Gin Tonic Bombay", ingredientes: "", price: 6900, id: "92"},
		{ category_id: "10", name: "Amargo obrero", ingredientes: "", price: 3500, id: "93"},
		{ category_id: "10", name: "Gancia", ingredientes: "", price: 4300, id: "94"},
		{ category_id: "10", name: "Gancia Hibiscus Tonic", ingredientes: "", price: 5400, id: "95"},
		{ category_id: "10", name: "Gancia Hibiscus Spritz", ingredientes: "", price: 5400, id: "96"},
		{ category_id: "10", name: "Martini Blanco", ingredientes: "", price: 4900, id: "97"},
		{ category_id: "10", name: "Martini Rosso", ingredientes: "", price: 4900, id: "98"},
		{ category_id: "10", name: "Fernet Branca", ingredientes: "con coca cola", price: 5200, id: "99"},
		{ category_id: "10", name: "Ron Bacardí", ingredientes: "", price: 5200, id: "100"},
		{ category_id: "10", name: "Negroni", ingredientes: "", price: 5200, id: "101"},
		{ category_id: "10", name: "Aperol Spritz", ingredientes: "", price: 5200, id: "102"},
		{ category_id: "10", name: "Campari", ingredientes: "con jugo de naranja", price: 5400, id: "103"},
		{ category_id: "10", name: "Lemoncello", ingredientes: "", price: 2800, id: "104"},
	])
}
